apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    method: fromcode
    run: nginx
name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-yaml
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
