apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-joel
  name: deploy-joel
spec:
  replicas: 10
  selector:
    matchLabels:
      app: deploy-joel
  template:
    metadata:
      labels:
        app: deploy-joel
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
  strategy:
    type: Recreate

